- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started

    - name: Copy file with owner and permission, using symbolic representation
      copy:
        src: ./medicurelb.yml
        dest: /home/ubuntu/medicurelb.yml
        owner: ubuntu
        group: ubuntu
        mode: "0644"

    - name: Install kubectl
      apt:
        name: kubectl
        state: present

    - name: Run container
      shell: kubectl apply -f /home/ubuntu/medicurelb.yml
      become_user: ubuntu
