- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io
    become : yes
    become_user : root

  - name : Start Docker Service
    command : sudo systemctl start docker
    become : yes
    become_user : root
    
  - name : Download kubectl repo
    command : curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    become : yes
    become_user : root  
    
  - name : Install kubectl
    command : sudo install -o jenkins -g jenkins -m 0755 kubectl /usr/local/bin/kubectl
    become : yes
    become_user : root       
    

  - name: Copy file with owner and permission, using symbolic representation
    ansible.builtin.copy:
      src: ./medicurelb.yml
      dest: /home/ubuntu/medicurelb.yml
      owner: ubuntu
      group: ubuntu
      mode: u=rw,g=r,o=r
   
  - name : run container
    command : kubectl apply -f /home/ubuntu/medicurelb.yml
    become : yes
    become_user : ubuntu
